import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import WhatsAppButton from "@/components/basic/whatsapp-button";
import { readNavbarData } from "@/services/navbar";
import { readFooterSection } from "@/services/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navData = await readNavbarData();
  const footerData = await readFooterSection();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar navData={navData} />
        {children}
        <Footer footerData={footerData}/>
        <WhatsAppButton phoneNumber="0344-1243567" />
      </body>
    </html>
  );
}
